provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  foo:
    lang: dockerfile
    handler: ./foo
    image: foo:latest
  bar:
    lang: dockerfile
    handler: ./bar
    image: bar:latest
